CREATE TABLE USER (
  id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL
);

CREATE TABLE ITEM (
  id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  owner_id INTEGER NOT NULL,
  name VARCHAR(255) NOT NULL,
  size VARCHAR(128) NOT NULL,
  link VARCHAR(512) NOT NULL,
  FOREIGN KEY (owner_id) REFERENCES USER(id) ON DELETE CASCADE
);
